apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- deployment.yaml
- service.yaml
images:
- name: jorgehsrocha21/argocd
  newTag: d4232b19f220562193ea6fa8e4237e880c72e294
