apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: argocdimage
    newName: jorgehsrocha21/argocd
    newTag: latest
