apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: argocdimage
  newName: jorgehsrocha21/argocd
  newTag: latest
- name: jorgehsrocha21/argocd
  newTag: 6bec910378e2307627a5e4e9774ea95590a43694
